---
title: "tian_model_selection"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(broom)
library(HH) 
library(leaps)
library(caret)
library(modelr)
library(faraway)
```

# initial full model
```{r}
data = read_csv("./data/Cancer_Registry.csv") %>% 
  janitor::clean_names()
```

Transformation decision mainly based on "margaret_eda.md"
Full model variables exclude variables with high-linearity.
```{r}
data_trans = data %>% 
  mutate(log_avg_ann_count = log(avg_ann_count)) %>% 
  mutate(study_per_cap = recode(study_per_cap, "0" = 0.001)) %>% #fix "-inf" problem
  mutate(log_study_per_cap = log(study_per_cap)) %>% 
  mutate(sqrt_pct_bach_deg18_24 = sqrt(pct_bach_deg18_24)) %>% 
  mutate(log_pct_bach_deg25_over = log(pct_bach_deg25_over)) %>% 
  mutate(sqrt_pct_unemployed16_over = sqrt(pct_unemployed16_over)) %>% 
  mutate(pct_asian = recode(pct_asian, "0" = 0.001)) %>% #fix "-inf" problem
  mutate(log_pct_asian = log(pct_asian)) %>% 
  mutate(pct_other_race = recode(pct_other_race, "0" = 0.001)) %>% #fix "-inf" problem
  mutate(log_pct_other_race = log(pct_other_race)) %>% 
  dplyr::select(target_death_rate, log_avg_ann_count, incidence_rate, med_income, poverty_percent,  log_study_per_cap, median_age_male, median_age_female, avg_household_size, percent_married, pct_no_hs18_24,  pct_hs18_24, sqrt_pct_bach_deg18_24, pct_hs25_over, log_pct_bach_deg25_over, sqrt_pct_unemployed16_over,  pct_emp_priv_coverage, pct_black, log_pct_asian, log_pct_other_race, pct_married_households, birth_rate)

model_full =
  lm(target_death_rate ~ log_avg_ann_count + incidence_rate + med_income + poverty_percent + log_study_per_cap + median_age_male + median_age_female + avg_household_size + percent_married + pct_no_hs18_24 + pct_hs18_24 + sqrt_pct_bach_deg18_24 + pct_hs25_over + log_pct_bach_deg25_over + sqrt_pct_unemployed16_over + pct_emp_priv_coverage + pct_black + log_pct_asian + log_pct_other_race + pct_married_households + birth_rate, data = data_trans) #21 variables
```

# Method 1 stepwise

```{r}
step(model_full, direction = 'backward')
```

```{r}
model_step = lm(formula = target_death_rate ~ log_avg_ann_count + incidence_rate + poverty_percent + median_age_male + percent_married + pct_no_hs18_24 + pct_hs18_24 + sqrt_pct_bach_deg18_24 + pct_hs25_over + log_pct_bach_deg25_over + sqrt_pct_unemployed16_over + pct_black + log_pct_other_race + pct_married_households + birth_rate, data = data_trans)
summary(model_step) #p-value?
```


# Method 2 criterion-based (>8?)

```{r criterion}
data_trans = as.data.frame(data_trans)
# Leaps function provides all-subsets analysis
# Printing the 2 best models of each size, using the Cp criterion:
leaps(x = data_trans[,2:22], y = data_trans[,1], nbest = 2, method = "Cp")
# Printing the 2 best models of each size, using the adjusted R^2 criterion:
leaps(x = data_trans[,2:22], y = data_trans[,1], nbest = 2, method = "adjr2")

# Summary of models for each size (one model per size)
rs = summary(regsubsets(target_death_rate ~ ., data = data_trans))

par(mfrow = c(1,2))

plot(2:9, rs$cp, xlab = "No of parameters", ylab = "Cp Statistic")
abline(0,1)

plot(2:9, rs$adjr2, xlab = "No of parameters", ylab = "Adj R2")
```

